// Code generated by MockGen. DO NOT EDIT.
// Source: scaffolds/repo.go

package scaffolds

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/izumin5210/scaffold/entity"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return _m.recorder
}

// GetAll mocks base method
func (_m *MockRepository) GetAll() ([]*entity.Scaffold, error) {
	ret := _m.ctrl.Call(_m, "GetAll")
	ret0, _ := ret[0].([]*entity.Scaffold)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (_mr *MockRepositoryMockRecorder) GetAll() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetAll")
}
