// Code generated by MockGen. DO NOT EDIT.
// Source: context.go

package app

import (
	gomock "github.com/golang/mock/gomock"
	scaffold "github.com/izumin5210/scaffold/domain/scaffold"
)

// MockContext is a mock of Context interface
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
}

// MockContextMockRecorder is the mock recorder for MockContext
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockContext) EXPECT() *MockContextMockRecorder {
	return _m.recorder
}

// RootPath mocks base method
func (_m *MockContext) RootPath() string {
	ret := _m.ctrl.Call(_m, "RootPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// RootPath indicates an expected call of RootPath
func (_mr *MockContextMockRecorder) RootPath() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RootPath")
}

// TemplatesPath mocks base method
func (_m *MockContext) TemplatesPath() string {
	ret := _m.ctrl.Call(_m, "TemplatesPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// TemplatesPath indicates an expected call of TemplatesPath
func (_mr *MockContextMockRecorder) TemplatesPath() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TemplatesPath")
}

// Repository mocks base method
func (_m *MockContext) Repository() scaffold.Repository {
	ret := _m.ctrl.Call(_m, "Repository")
	ret0, _ := ret[0].(scaffold.Repository)
	return ret0
}

// Repository indicates an expected call of Repository
func (_mr *MockContextMockRecorder) Repository() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Repository")
}
