// Code generated by MockGen. DO NOT EDIT.
// Source: fs/fs.go

package fs

import (
	gomock "github.com/golang/mock/gomock"
)

// MockFS is a mock of FS interface
type MockFS struct {
	ctrl     *gomock.Controller
	recorder *MockFSMockRecorder
}

// MockFSMockRecorder is the mock recorder for MockFS
type MockFSMockRecorder struct {
	mock *MockFS
}

// NewMockFS creates a new mock instance
func NewMockFS(ctrl *gomock.Controller) *MockFS {
	mock := &MockFS{ctrl: ctrl}
	mock.recorder = &MockFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockFS) EXPECT() *MockFSMockRecorder {
	return _m.recorder
}

// GetDirs mocks base method
func (_m *MockFS) GetDirs(path string) ([]string, error) {
	ret := _m.ctrl.Call(_m, "GetDirs", path)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirs indicates an expected call of GetDirs
func (_mr *MockFSMockRecorder) GetDirs(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetDirs", arg0)
}

// ReadFile mocks base method
func (_m *MockFS) ReadFile(path string) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "ReadFile", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile
func (_mr *MockFSMockRecorder) ReadFile(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReadFile", arg0)
}
