// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go

package factory

import (
	gomock "github.com/golang/mock/gomock"
	scaffold "github.com/izumin5210/scaffold/domain/scaffold"
	cli "github.com/mitchellh/cli"
)

// MockFactory is a mock of Factory interface
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return _m.recorder
}

// CreateCreateScaffoldCommandFactory mocks base method
func (_m *MockFactory) CreateCreateScaffoldCommandFactory(sc *scaffold.Scaffold) cli.CommandFactory {
	ret := _m.ctrl.Call(_m, "CreateCreateScaffoldCommandFactory", sc)
	ret0, _ := ret[0].(cli.CommandFactory)
	return ret0
}

// CreateCreateScaffoldCommandFactory indicates an expected call of CreateCreateScaffoldCommandFactory
func (_mr *MockFactoryMockRecorder) CreateCreateScaffoldCommandFactory(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateCreateScaffoldCommandFactory", arg0)
}
